# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-05-16 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='books',
            field=models.ManyToManyField(to='books.Book'),
        ),
    ]
